ИЗ1
23-yo-designer-from-san-francisco/hw1_c pull request #1
Opened 2021-03-12 10:56 UTC by 23-yo-designer-from-san-francisco

2021-03-13 16:23 UTC, let-robots-reign requested changes

2021-03-13 16:23 UTC, let-robots-reign commented on .travis.yml
> +   - grep -q "no leaks are possible" valgrind.log
Хорошо бы фейлить сборку, если cppcheck или valgrind не проходит

2021-03-13 16:23 UTC, let-robots-reign commented on include/algorithm.h
> +size_t **max_area(const double*, const double*, const int);
По названию функции `max_area` на первый взгляд может показаться, что она должна возвращать число, соответствующее площади, но на самом деле она возвращает координаты точек, составляющих треугольник с максимальной площадью. Мне кажется, что это нужно отразить в названии функции (например, `get_max_triangle` или что-то похожее).
Почему решил использовать тип `int` для параметра, обозначающего размер?

2021-03-13 16:23 UTC, let-robots-reign commented on main.c
> +int main(int argc, char *argv[]) {
Функция main не должна содержать никакой логики внутри себя, она должна вызывать функции ввода/обработки/вывода

2021-03-13 16:23 UTC, let-robots-reign commented on main.c
> +        return -1;
Не думаю, что в ИЗ1 ожидается ввод с помощью аргументов командной строки. В этом задании нужно построить корректное взаимодействие с пользователем: предложение к вводу данных, ввод и проверка на ошибки, вывод с пояснением, что было выведено

2021-03-13 16:23 UTC, let-robots-reign commented on main.c
> +        return -1;
У тебя -1 возвращается для всех ошибок. Так программист не сможет сразу понять, в каком именно месте упала программа: то ли это ошибка выделения памяти, то ли были переданы невалидные параметры, как дальше в коде. Лучше определить несколько ошибок и возвращать их в каждом конкретном случае.

2021-03-13 16:23 UTC, let-robots-reign commented on src/algorithm.c
> +#include "../include/algorithm.h"
Относительный путь тут не нужен, так как ты уже прописал папку include в команде `include_directories`. `#include "algorithm.h"` будет достаточно.

2021-03-13 16:23 UTC, let-robots-reign commented on src/algorithm.c
> +    if (!a || !b || ARR_SIZE < 3) {
Лучше вынести захардкоженное число "3". В функции `free_result` аналогично

2021-03-13 16:23 UTC, let-robots-reign commented on src/algorithm.c
> +        return NULL;
В main при ошибке выделения памяти возвращается -1, здесь возвращается NULL, надо бы привести к единому поведению

2021-03-13 16:23 UTC, let-robots-reign commented on test/algorithm.cpp
> +    EXPECT_TRUE(max_area(NULL, NULL, 0) == NULL);
Для сравнения в gtest чаще используется ASSERT_EQ или EXPECT_EQ

2021-03-13 16:27 UTC, 23-yo-designer-from-san-francisco commented on .travis.yml
> +   - grep -q "no leaks are possible" valgrind.log
Если что-либо не пройдет, оно вернет код, отличный от `0`, и тесты зафейлятся. Проверено. Можно было даже не grep'ать "no leaks are possible", т.к. если valgrind не пройдет, он вернет код, отличный от `0` но если строка не будет найдена, тесты упадут.

2021-03-13 16:32 UTC, 23-yo-designer-from-san-francisco commented on include/algorithm.h
> +size_t **max_area(const double*, const double*, const int);
С замечанием по поводу названия согласен.

Использовал `int` для размера по ошибке, руководствуясь тем, что программа берет аргументы из `argv` в количестве `argc` (а это `int`). Хотя, естественно, логика находится в отдельном файле и ее не должно волновать, откуда я беру аргументы. Очевидно, там должен быть `size_t` .

2021-03-13 16:43 UTC, 23-yo-designer-from-san-francisco commented on src/algorithm.c
> +        return NULL;
Т.к. функция возвращает указатель, мне кажется, будет неправильно возвращать что-то отличное от `NULL` конкретно здесь. Если же привести другие функции к виду "возвращает `NULL`", тогда программист не поймет, что же с программой не так, т.к. кода ошибки нет (по факту у меня и сейчас так с `-1`)

2021-03-13 16:46 UTC, 23-yo-designer-from-san-francisco commented on test/algorithm.cpp
> +    EXPECT_TRUE(max_area(NULL, NULL, 0) == NULL);
Пробовал и хотел сделать так, но возникает

`.../gtest.h:1527:11: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
 1527 |   if (lhs == rhs) {`

2021-03-13 17:15 UTC, let-robots-reign commented on test/algorithm.cpp
> +    EXPECT_TRUE(max_area(NULL, NULL, 0) == NULL);
Хорошо, убираем это замечание)
Тогда можно просто
`EXPECT_FALSE(max_area(NULL, NULL, 0))`

2021-03-13 17:23 UTC, let-robots-reign commented
Также не хватает отчета по покрытию кода тестами. Рекомендую прочитать про `lcov` и как им пользоваться для генерации отчета по покрытию, а также про то, как генерацию отчетов интегрировать с Travis CI (например, использовать [codecov](https://about.codecov.io/))

2021-03-15 16:25 UTC, Vinograduss commented on src/io.c
> +            return NULL;
у тебя будет утечка памяти, если одно из условий не выполнится.

ты выделяешь память перед циклом, а в цикле делаешь return и при этом память не освобождаешь

2021-03-15 16:25 UTC, Vinograduss commented on src/io.c
> +    if (*arr_size < 3) {
число `3` в коде является магическим числом, кажется его стоит оформить в виде переменной

2021-03-15 16:25 UTC, Vinograduss commented on src/io.c
> +    double *y = (double*)malloc(sizeof(double) * (*arr_size));
в рамках ИЗ12 мы просим делать проверки на выделение памяти и перевыделение памяти

2021-03-15 16:25 UTC, Vinograduss commented on main.c
> +
а заче выделять память под arr_size динамически?

2021-03-15 16:25 UTC, Vinograduss commented on src/algorithm.c
> +    size_t *point3 = (size_t*)malloc(sizeof(size_t));
зачем под эти три переменные выделять память динамически?

2021-03-15 16:25 UTC, Vinograduss commented on src/algorithm.c
> +    size_t **result = (size_t **)malloc(sizeof(size_t *) * 3);
под эту `3`  у тебя уже есть даже переменная )

2021-03-15 16:25 UTC, Vinograduss commented on test/algorithm.cpp
> +
мало тестов, надо добавить

2021-03-25 14:43 UTC, merged